apiVersion: v1
kind: Namespace
metadata:
  name: urcuchillay-chat
---
apiVersion: v1
kind: Secret
metadata:
  namespace: urcuchillay-chat
  name: urcuchillay-chat
type: Opaque
data:
  OPENAI_API_KEY: <base64 encoded key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: urcuchillay-chat
  name: urcuchillay-chat
  labels:
    app: urcuchillay-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urcuchillay-chat
  template:
    metadata:
      labels:
        app: urcuchillay-chat
    spec:
      containers:
        - name: urcuchillay-chat
          image: castellotti/urcuchillay-chat:latest
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: urcuchillay-chat
                  key: OPENAI_API_KEY
---
kind: Service
apiVersion: v1
metadata:
  namespace: urcuchillay-chat
  name: urcuchillay-chat
  labels:
    app: urcuchillay-chat
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: urcuchillay-chat
  type: ClusterIP
